server:
  port: 8761

spring:
  application:
    name: discoveryservice
#  cloud:
#    config:
#      uri: http://13.209.133.82:8888
#      name: ecommerce
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false